### ISSUE TITLE
Discord Reborn: Button not work

### ISSUE THREAD

**Issue by ak47Default168** [0mniscient/Discord-Themes#106]
The theme made a button not working, while I play a game
I cannot extend to send a invite and upload a File
![osu 1](https://user-images.githubusercontent.com/26413893/32375314-1e4d09d2-c0dc-11e7-83d9-54cdd25dd7b7.PNG)
![osu](https://user-images.githubusercontent.com/26413893/32375316-1f63173a-c0dc-11e7-86ef-50621ca58b4b.PNG)
this button

**Comment by squee666** [comment]
cant replicate that button popout which is probably why we never fixed it
