### ISSUE TITLE
Theme not loading properly?

### ISSUE THREAD

**Issue by GeneralWarPig** [0mniscient/Discord-Themes#116]
Theme does not to be able to load fully, upper left is normal open/close/minimize icons, etc.
![capture](https://user-images.githubusercontent.com/33412950/32429588-e7301be0-c290-11e7-92c7-3200e5e7afc0.PNG)

**Comment by squee666** [comment]
im gonna help you spanky 

<----- Left                                                                                  Right ------->

Also theme loads fine try turning it off and looking at top *left* again you will see the bar is to do with stock
