### ISSUE TITLE
Looks like discord changed the user profile again, and broke the CSS there

### ISSUE THREAD

**Issue by SupDos** [0mniscient/Discord-Themes#12]
Theme Enabled - https://b.catgirlsare.sexy/TlEI.png
Theme Disabled - https://b.catgirlsare.sexy/-ebD.png
Another Example - https://b.catgirlsare.sexy/0dAn.png

**Comment by 0mniscient** [comment]
Forgot to fix that on this theme i'll fix it

**Comment by SupDos** [comment]
Awesome, thanks

**Comment by 0mniscient** [comment]
fixed
