### ISSUE TITLE
Reborn: Needs a copy with :only-child for when members bar is hidden and max-width < 970

### ISSUE THREAD

**Issue by just-Addict** [0mniscient/Discord-Themes#121]
https://github.com/0mniscient/Discord-Themes/blob/512ec06bfd056cba3f16fcc1a8c2f9c8bd3dfc7b/css/Quiet.css#L4195

this selector needs a copy with :only-child added to set margin back to zero so chat does not go off-screen when the members bar is turned off and max-width is less than 970

This does however require the !important to be removed from this margin.

**Comment by DacioRomero** [comment]
I was just about to report this as it has been a problem for a while. It's extremely annoying as it I use Discord in one of my secondary monitors which is 900x1400 (portrait) and can't see what I'm typing until the text wraps back around. I don't know how, but it needs to be made smaller or just hidden.

This is what it looks like:
![image](https://user-images.githubusercontent.com/12436128/34131163-7d000632-e418-11e7-8256-89c6487834d8.png)

**Comment by squee666** [comment]
added it
