### ISSUE TITLE
helper icon overlays the minimize button on Quiet Theme

### ISSUE THREAD

**Issue by rwkyyy** [0mniscient/Discord-Themes#14]
Hi there,

Just noticed that the "?" Icon that is hidden through the theme, overlays with the minimize "_" button.

Although it's hidden, it still has the functionality.

**Comment by 0mniscient** [comment]
Sigh I tried many ways to hide it but I guess I'll just revert it back to normal

**Comment by rwkyyy** [comment]
I know, I tried myself, but didn't find any viable solutions :(

**Comment by rwkyyy** [comment]
looks like removing lines from 1660 to 1665, cancels the mods in that area and everything is back to normal.

**Comment by 0mniscient** [comment]
Will do. I'm at school atm will be home in a couple of hours
