### ISSUE TITLE
Discord freezes after going on fullscreen with videos

### ISSUE THREAD

**Issue by mamimamicuzpipi** [0mniscient/Discord-Themes#19]
Everytime I try to play a video on fullscreen with Discord Reborn it freezes 1-2 secs after playing it.

This has happened with YouTube videos and Twitch clips, I don't know if it also happens with other sites.

**Comment by Flobberz** [comment]
This is still happening to this day, the video just freezes and only closing discord from task manager unfreezes it, it also uses a tremendous amount of CPU when that happens.
