### ISSUE TITLE
Fancy name in discord reborn theme

### ISSUE THREAD

**Issue by SnarkyLobster** [0mniscient/Discord-Themes#211]
Do I really need my discord name in the lower right corner? removing it as a stylistic choice would be nice, not to mention that since I use the smallest possible discord window, it's overlapping my emote button in DMs, rendering it unusable until I've written 'enough' to pop it up over the name, even fiddling with zoom and text sizing. E.g. [here](https://i.gyazo.com/9453528b301858dbd2568ac58a59f830.png). I love the rest of the theme, but this one thing bugs me now and then.

**Comment by cubeguy** [comment]
As I always say, you get a faster response on the support server, but here's the css to revert it to a more vanilla style:
`/*Revert account details text — vanilla */
#app-mount .accountDetails-15i-_e {position:unset !important; min-width:unset !important;bottom:0px !important;height: unset !important;transform: translateY(-25px) !important;}
#app-mount .accountDetails-15i-_e .username { margin-left: unset !important; border: none !important; font-family:Whitney,Helvetica Neue,Helvetica,Arial,sans-serif !important; font-size:15px !important; font-weight:700 !important; color:white !important; text-align:unset !important; height:30px!important; line-height:10px!important; text-shadow: 0.5px 0.5px 2px black!important; }
.accountDetails-15i-_e .discriminator {display: inline-block !important; font-size: 12px !important;text-shadow: 0.5px 0.5px 2px black!important; position: unset !important;transform: translate(-94px, 14px) !important;margin-bottom: 20px;}
.accountDetails-15i-_e + div div{margin-left:unset !important;}
.accountDetails-15i-_e .username {background-color: transparent !important;}
.channel-members::after {display: none;}
[class*="scroller-"].channel-members {height: 100%!important;padding-top: 8px;}
.private .channelTextArea-os01xC {margin: 20px 0 32px 0!important}
.accountDetails-15i-_e + div div {margin-left: 0px !important;}`

**Comment by SnarkyLobster** [comment]
Thank you so much, this is perfect!
 

    On Saturday, December 30, 2017 4:40 PM, Matt <notifications@github.com> wrote:
 

 As I always say, you get a faster response on the support server, but here's the css to revert it to a more vanilla style:
/*Revert account details text — vanilla */ #app-mount .accountDetails-15i-_e {position:unset !important; min-width:unset !important;bottom:0px !important;height: unset !important;transform: translateY(-25px) !important;} #app-mount .accountDetails-15i-_e .username { margin-left: unset !important; border: none !important; font-family:Whitney,Helvetica Neue,Helvetica,Arial,sans-serif !important; font-size:15px !important; font-weight:700 !important; color:white !important; text-align:unset !important; height:30px!important; line-height:10px!important; text-shadow: 0.5px 0.5px 2px black!important; } .accountDetails-15i-_e .discriminator {display: inline-block !important; font-size: 12px !important;text-shadow: 0.5px 0.5px 2px black!important; position: unset !important;transform: translate(-94px, 14px) !important;margin-bottom: 20px;} .accountDetails-15i-_e + div div{margin-left:unset !important;} .accountDetails-15i-_e .username {background-color: transparent !important;} .channel-members::after {display: none;} [class*="scroller-"].channel-members {height: 100%!important;padding-top: 8px;} .private .channelTextArea-os01xC {margin: 20px 0 32px 0!important} .accountDetails-15i-_e + div div {margin-left: 0px !important;}—

**Comment by squee666** [comment]
reason for closing is the bottom right name got reverted in the main theme
