### ISSUE TITLE
Discord Reborn isn't acting right

### ISSUE THREAD

**Issue by ZXNova** [0mniscient/Discord-Themes#23]
When I open up discord or use ctrl+R to reset it, the theme doesn't seem to load up. I'm just left with a completely black void, but I still have the custom CSS from discord reborn. Not only that, but when I go to settings the theme I'm using pops up. I've checked the url for the image I'm using and it's just fine. Could this be an issue with imgur or is discord reborn just messing up? 

Screenshots: http://i.imgur.com/tVGGd1p.jpg (Black Void but CSS is still active)
http://i.imgur.com/qlyHfq1.jpg?1 (When I open up settings)

**Comment by 0mniscient** [comment]
Discord did a silent update and changed a bit of CSS I will fix soon
