### ISSUE TITLE
Issues with Quiet

### ISSUE THREAD

**Issue by OblivionNW** [0mniscient/Discord-Themes#34]
1. https://gyazo.com/0566e394163160616843cc966d56bb71 - It tells you to redownload Quiet but the link is a 404, I had to replace my current file with the one in this GitHub repo for it to work.
2. The css file in the GitHub causes this - https://gyazo.com/47b8a110cb6bf7b88f41c2079d777265 (Help button overlaps others)

**Comment by 0mniscient** [comment]
That url should be correct.
The second part is incomplete css my bad let me comment that out. It's something im working on.

**Comment by OblivionNW** [comment]
Oh! That's my bad - I read it as betterdiscord.net

**Comment by Firefly1029** [comment]
The update doesn't work at all for me. BD doesn't recognize it, Would have been so much simpler if you just didn't make the old version unusable.

**Comment by DiscordCollab** [comment]
all you have to do (if you still have the old theme) is open the theme file with a note pad editor of some kind and just remove the _2 from the url (@import url) and it should work.

**Comment by 0mniscient** [comment]
all you have to do (if you still have the old theme) is open the theme file with a note pad editor of some kind and just remove the _2 from the url (@import url) and it should work.
