### ISSUE TITLE
bug on Mac

### ISSUE THREAD

**Issue by GonBust5** [0mniscient/Discord-Themes#36]
Hey im using a Mac and the theme now as a bug it did not have before :c
<img width="398" alt="captura de ecra 2017-04-13 as 12 38 07" src="https://cloud.githubusercontent.com/assets/22590506/25003264/6fc97818-2046-11e7-9a17-afe49f87e543.png">
will wait for fix
love this theme keep up the good work :)

**Comment by 0mniscient** [comment]
I have no one on Mac that knows css atm so anyone using Mac will have to wait patiently
