### ISSUE TITLE
Is there any way I can change the brightness?

### ISSUE THREAD

**Issue by LambsFatAss** [0mniscient/Discord-Themes#4]
I really like the Discord Reborn theme but I cannot for the life of me find where I can change the brightness of the background, I know it's supposed to be dark but I want to just make it brighter. 
I have played around with tons of values and can't find it, if you could let me know I would really appreiciate it. If possible I want to make it as bright as when you hit settings.

Thanks.

**Comment by 0mniscient** [comment]
Sorry for the late reply Member List:.channel-members {background: rgba(0, 0, 0, 0.9)!important;} Messages (Middle Area):.content .flex-spacer {    background: rgba(0, 0, 0, 0.85);}Channel List:.channels-wrap {    background: rgba(0, 0, 0, 0.75);}Server List:.guilds {    background-color: rgba(0, 0, 0, 0.6) !important;}
Date: Sun, 24 Jul 2016 07:31:19 -0700
