### ISSUE TITLE
Discord Reborn bug

### ISSUE THREAD

**Issue by krass09** [0mniscient/Discord-Themes#41]
After accidentally applying the KMS theme, Discord Reborn theme become broken. Neither image in background nor styles are not applicable. Have tried to reinstall BetterDiscord. Result the same.

**Comment by 0mniscient** [comment]
Move out all themes and re download reborn and test if it works

**Comment by krass09** [comment]
Firstly it not worked.
Then I just deleted the whole BetterDiscord folder and reinstalled the app. Added abovementioned theme into new betterdiscord folder, started discord. So, after several attempts to launch the discord app, it finally worked for me.
Problem solved. Still puzzled why it had occured.
