### ISSUE TITLE
custom background in theme:quiet

### ISSUE THREAD

**Issue by raymondvansomeren** [0mniscient/Discord-Themes#44]
I've tried some thing but none worked. One of the things i tried was adding:
`.callout-backdrop {
	background:url(https://i.imgur.com/mCUIYtx.jpg) !important;
    background-size:cover !important;
}`
in the css file, but that's probably not right... I added it before 
`:root { 
 --main-color: #8d2036;
 --hover-color: #6f182a;
 }`.
Can you please help me?

Kind regards,

Raymond.

**Comment by 0mniscient** [comment]
That's because Quiet isn't a transparent theme. It's a solid color theme which means you can't add a background picture just like that you would need to add CSS to make some elements transparent and I'm not doing that any time soon.
