### ISSUE TITLE
[Discord Reborn 6] PTB Channel List Bug

### ISSUE THREAD

**Issue by raxixor** [0mniscient/Discord-Themes#45]
The channel list looks like the default dark mode.

Image of the issue:
![image](https://cloud.githubusercontent.com/assets/1861988/26750287/6563d356-4827-11e7-8edb-a70dc79bf18a.png)

**Comment by 0mniscient** [comment]
Fixing

**Comment by GriffinG1** [comment]
Update that included this just hit discord

**Comment by Jfamig** [comment]
There seems to be some broken elements from this updatebreak on Quiet too

**Comment by ryudragon98** [comment]
many elements in reborn are the default dark mode color instead of the theme color
