### ISSUE TITLE
[Quiet] New channel list formatting

### ISSUE THREAD

**Issue by LWTechGaming** [0mniscient/Discord-Themes#46]
This issue is probably not only affecting Quiet, but I'm using that anyways and hence reporting for it.

Due to the rework that happened with the channel list on stable today, the CSS does not reflect this. At least the channel list element does not have formatting applied, unsure if further discrepancies exist. Screenie below.

![Example](http://images.lwtechgaming.me/AB5IOj8.png)

**Comment by cursedcookies** [comment]
It affects the dm buttons too as well as the friends button. u-u

**Comment by AdriMartinGlez** [comment]
yep i have this exact same problem. Hope someone fix it cause every single theme looks bad like this

**Comment by GenesisAria** [comment]
It affecting other themes as well for sure (i use Reborn).
