### ISSUE TITLE
Quiet text in the way of people inside the channel

### ISSUE THREAD

**Issue by Fiskpung** [0mniscient/Discord-Themes#47]
Image of issue:
![b3249347c342e6b0f0dfac662e758ee3](https://user-images.githubusercontent.com/29520468/27261236-45f268e2-543f-11e7-8d38-2a66b52b1c11.png)

**Comment by Jfamig** [comment]
That is a brand new problem. I just got it too.

**Comment by 0mniscient** [comment]
Fixed.

**Comment by Fiskpung** [comment]
Thanks, much appreciated. love the theme, dark and smooth, yet amazing (y)
