### ISSUE TITLE
No number of people adding reactions.

### ISSUE THREAD

**Issue by RikoDEV** [0mniscient/Discord-Themes#49]
When someone adds a reaction, they see the number of people who added the reaction. When I add reactions to this message I can not see the number of people who have already done so.

**Theme:** Quiet

![ss](https://user-images.githubusercontent.com/18230443/27507171-0eefd0c0-58ca-11e7-8e88-89c3a4dca77c.PNG)

**Comment by 0mniscient** [comment]
It's a betterdiscord thing
Settings>BetterDiscord>BD Blue
Turn it off.
