### ISSUE TITLE
[bug] Quiet -- compact mode makes usernames and chat clip left off off that app.

### ISSUE THREAD

**Issue by JourneyOver** [0mniscient/Discord-Themes#5]
If using Quiet and have compact mode turned on on discord, it seems to end up pushing chat to the left which in turn clips off parts of usernames and text..

http://i.imgur.com/U053DbD.png shows an example of what I mean.

**Comment by Efreak** [comment]
Just came here to report this. Also, please add a link in the theme description--finding the theme again was difficult because no google results.

**Comment by 0mniscient** [comment]
I have an idea as in why this is happening I will fix tomorrow.

**Comment by 0mniscient** [comment]
I lied I decided to fix it now
