### ISSUE TITLE
Discord Reborn now Using the quiet theme

### ISSUE THREAD

**Issue by izzy420** [0mniscient/Discord-Themes#61]
https://i.imgur.com/fdSGafc.jpg

I did a restart today and suddenly the quiet theme is in use 

Tried reinstalling the css etc.

https://github.com/0mniscient/Discord-Themes/blob/master/css/Discord%20Reborn.css

The Reborn CSS links to the quiet CSS which is the cause it seems

**Comment by 0mniscient** [comment]
I will look into this issue atm I'm not home
