### ISSUE TITLE
Muted Categories are glitchy | Quiet Theme

### ISSUE THREAD

**Issue by PixeLInc** [0mniscient/Discord-Themes#66]
As seen here: https://i.imgur.com/RFpiqCf.png
The text when a category is muted is down there and doesn't feature the lines like the other unmuted ones
Also, sometimes when you try and hover over the muted category to collapse and uncollapse it, it tends to glitch out a little bit:
https://i.imgur.com/m2XdmGK.gifv

**Comment by DacioRomero** [comment]
I'm having a similar problem, I just don't mute categories for now until it's (hopefully) fixed.
