### ISSUE TITLE
Quiet Theme: Member List Pulsating Effect Offset to the Left

### ISSUE THREAD

**Issue by DacioRomero** [0mniscient/Discord-Themes#67]
When normally the member list has just shapes and is pulsating without the theme applied, Quiet shows the member list, but the pulsating effect is offset the the left when at 700 pixels or less in width. The pulsating effect is also more of a scrolling back and forth of a transparent gradient, not sure if this is purposeful.

**Comment by DacioRomero** [comment]
I was experiencing this problem on the main BetterDiscord server.

**Comment by 0mniscient** [comment]
That's because the server is loading the members section thats Discords loading animation so its really not my problem the only reason this happens in the bd server is because its so large it wont even load the member list
