### ISSUE TITLE
Quiet Theme: If Very First Element is a Category It isn't as Indented

### ISSUE THREAD

**Issue by DacioRomero** [0mniscient/Discord-Themes#69]
[Image](https://imgur.com/a/n1nRi)

**Comment by DacioRomero** [comment]
Nearly fixed, but still a little less indented.
![image](https://user-images.githubusercontent.com/12436128/31315152-895b5e2e-abe0-11e7-9fe6-5f307c71e31d.png)

**Comment by DacioRomero** [comment]
Also just realized there's a smaller gap between the first and second than the second and third.

**Comment by DacioRomero** [comment]
I almost feel like I should create a fork and just make pull requests if I can figure out how to fix it myself.

**Comment by 0mniscient** [comment]
If you can I'd appreciate that since i don't have much times on my hand now a days like I used to
