### ISSUE TITLE
Guild menu is getting cut off

### ISSUE THREAD

**Issue by shinji257** [0mniscient/Discord-Themes#7]
The guild menu on the top of the screen is getting cut off.  The cause is ".guild-header ul" in css.

Here is how it shows now.

![image](https://cloud.githubusercontent.com/assets/261005/18780078/dc098e9c-8149-11e6-9fd2-0d6c8caf0af1.png)

And fixed...

![image](https://cloud.githubusercontent.com/assets/261005/18780711/e5819b6a-814c-11e6-8d69-455cb8a2f865.png)

Easy fix.  Remove these lines...

padding-top:100px;
top:-56px;

From ".guild-header ul" so it looks like this:
.guild-header ul { background: rgba(0, 0, 0, 0.52) !important; transition: transform 0.5s cubic-bezier(0.18, 0.89, 0.32, 1.28) !important; }

I found this on another theme and it seems to affect a bunch of them out there.

**Comment by 0mniscient** [comment]
Fixed?
