### ISSUE TITLE
Quiet Theme: Members List has Inconsistent Gaps Between Each

### ISSUE THREAD

**Issue by DacioRomero** [0mniscient/Discord-Themes#70]
![image](https://user-images.githubusercontent.com/12436128/31314148-ec7215bc-abc6-11e7-8284-bbed53131a79.png)

Sorry for the number of issues that I'm submitting, just trying help. I hope you understand.

**Comment by DacioRomero** [comment]
I'm not sure why the Quiet logo and version number are right there either. But really good job on this theme, you're inspiring me to learn more about CSS because I didn't realize you could do that much with it.

**Comment by 0mniscient** [comment]
hmmm the Inconsistent gaps are because of the "now playing" some have it some dont and that quiet thing is a bug
