### ISSUE TITLE
Reaction Count

### ISSUE THREAD

**Issue by ZigZack47** [0mniscient/Discord-Themes#71]
The reaction count color and reaction count box color are the same once I've reacted to something, making me not able to read how many people in total have reacted with that emoji. https://i.imgur.com/qcZsGiC.png

**Comment by ZigZack47** [comment]
Sorry, I forgot to mention which theme this was occurring on, I'm using Discord Reborn.

**Comment by ryudragon98** [comment]
go into the core settings of better discord and turn off betterdiscord blue.

**Comment by HYPExMon5ter** [comment]
Issue should be closed as it's resolved.
