### ISSUE TITLE
Issues with upcoming Discord update [Major]

### ISSUE THREAD

**Issue by DaimeneX** [0mniscient/Discord-Themes#73]
I decided to come here and give an early warning about next upcoming update for Discord.
In latest Canary when you try to use Discord Reborn or any other type you encounter massive misalignment and the theme just doesn't work.

I assume it's mostly because of the newly added top bar.

Image of the issue.
![image](https://user-images.githubusercontent.com/27635283/31830079-7bd03e6c-b5bf-11e7-8056-a8cba6d92638.png)

**Comment by 0mniscient** [comment]
I already fixed it but won't be pushed until the update is out on stable
