### ISSUE TITLE
Broken Background and Layout

### ISSUE THREAD

**Issue by Aaeeschylus** [0mniscient/Discord-Themes#78]
As of today, the background image no longer works and the layout is broken in some places:

Image Proof: ![Image proof](https://puu.sh/y88vf/7895adfa40.png)

**Comment by Demonstoon** [comment]
Having exactly the same problem.

**Comment by LWTechGaming** [comment]
Yep, client update totally broke it.

**Comment by DaimeneX** [comment]
This issue was fixed as the Author was aware it was apparent in Canary release but didn't push it to avoid any problems with previous layout.
Now it's in Official and it's going to be fixed soon as far as I know

**Comment by 0mniscient** [comment]
Fixed
