### ISSUE TITLE
Stylish version of Discord Reborn no longer properly displays the background

### ISSUE THREAD

**Issue by Scrxtchy** [0mniscient/Discord-Themes#8]
Using Waterfox 49.0.2 (Firefox 49.0.1),
The userstyle sheet is properly applied, as it should be, but does not account for the background properly.
The image is applied and can be found if making some of the elements transparent (settings popup handles this nice https://jii.moe/NyzfHvERW.webm)

**Comment by 0mniscient** [comment]
youre right i wonder why im onto it.

**Comment by 0mniscient** [comment]
@Scrxtchy i found out why... i accidently erased like half of the css on the last update on userstyles whoops i could roll back but ima have to fix a couple small bugs
