### ISSUE TITLE
Persisting issues from the Discord format update

### ISSUE THREAD

**Issue by luxidoptera** [0mniscient/Discord-Themes#80]
So the Quiet theme has been mostly fixed since the vanilla Discord format update got pushed into Stable, but there are a couple of persisting issues from the initial broken period before the theme got updated. Here you can see both of the persisting issues I have seen thus far:

![image](https://user-images.githubusercontent.com/15697751/32149217-661b47e6-bcd7-11e7-81e3-91969404e2af.png)

The infobar on the bottom right is still out of alignment and pushed to the left, obscuring my info and just generally looking wrong, and the "[X user] is typing..." dialog appears in roughly the same location as the text box, instead of right above it like it should.

**Comment by EazyFTW** [comment]
Same issue here.

**Comment by 0mniscient** [comment]
Should be fixed ??

**Comment by EazyFTW** [comment]
A little bit but the bottom side is broken.

http://i.eazyftw.com/57-16:01:57.png

**Comment by EazyFTW** [comment]
Fixed, thanks.

**Comment by EazyFTW** [comment]
Oh. One thing. Issue with the text box exists, but is different. 

http://i.eazyftw.com/34-16:09:34.png
