### ISSUE TITLE
Typo in the welcome popup

### ISSUE THREAD

**Issue by SupDos** [0mniscient/Discord-Themes#9]
`body:before {
    content: "Thank's for using Discord Reborn!";`
The thanks doesn't have an apostrophe, so it should be "Thanks for using Discord Reborn!"
Also, is there any way we can disable this? It gets annoying after a while.

**Comment by 0mniscient** [comment]
Whoops and yea put this in Custom CSS

body:before { content: none !important; }
body:after { content: none !important; }
